#pragma once
#include "Graphics.h"

enum class Button
{

	NorthFace = SDL_GAMEPAD_BUTTON_NORTH,
	SouthFace = SDL_GAMEPAD_BUTTON_SOUTH,
	WestFace = SDL_GAMEPAD_BUTTON_WEST,
	EastFace = SDL_GAMEPAD_BUTTON_EAST,

	LeftBumper = SDL_GAMEPAD_BUTTON_LEFT_SHOULDER,
	RightBumper = SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER,

	Back = SDL_GAMEPAD_BUTTON_BACK,
	Start = SDL_GAMEPAD_BUTTON_START,

	DPadUp = SDL_GAMEPAD_BUTTON_DPAD_UP,
	DPadDown = SDL_GAMEPAD_BUTTON_DPAD_DOWN,
	DPadLeft = SDL_GAMEPAD_BUTTON_DPAD_LEFT,
	DPadRight = SDL_GAMEPAD_BUTTON_DPAD_RIGHT,

	LeftStickClick = SDL_GAMEPAD_BUTTON_LEFT_STICK,
	RightStickClick = SDL_GAMEPAD_BUTTON_RIGHT_STICK,
};